version: "3.8"

services:
  app:
    build: .
    container_name: student4-app
    ports:
      - "${APP_PORT}:${APP_PORT}"
    env_file:
      - .env
    volumes:
      - .env:/app/.env
    restart: always